name: sloc

on:
  push:
    branches:
      - main

jobs:
  sloc_py:
    env:
      TERM: xterm
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.x]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get install cloc
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: sloc count with cloc
      run: |
        make sloc
